// Gaps: {option1|correct*|option3::explanation}. Optional u: update id.
import type { Story } from "../lib/types";

export const STORIES: Story[] = [
{id:"s1", g:"ser, llamarse, género", t:"Paco se presenta", hr:"Paco je hobotnica iz Zaragoze i kuhar. Ima osam ruku pa radi brže od svih. Njegova prijateljica Lola je novinarka i Francuskinja. Lola pita gospodina Martíneza kako se zove i odakle je, a on je jako formalan.",
 text:`¡Hola! Me {llamo*|llama|llamas::yo → me llamo} Paco. {Soy*|Estoy|Tengo::Identitet i podrijetlo → SER} de Zaragoza. Soy un pulpo y {tengo*|soy|hay::imati → tener (tengo)} ocho brazos. Soy {cocinero*|cocinera|cocina::muški rod: -o} en un restaurante y cocino muy rápido. Mi amiga Lola es {francesa*|francés|franceso::francés → francesa} y es {periodista*|periodisto|periodistora::-ista je isto za oba roda}. Un día Lola habla con un señor muy serio: — Buenos días, ¿cómo se {llama*|llamas|llamo::usted → se llama} usted? — Me llamo Martínez. — ¿Y de dónde {es*|eres|está::usted → es} usted? — De Toledo. Mucho {gusto*|gusta|gustan::Mucho gusto = drago mi je}. Paco dice: «¡Encantado!» y le da la mano. Las ocho manos.`},
{id:"s2", g:"familia, posesivos, este / esta", t:"Una familia rara", hr:"Paco predstavlja svoju obitelj. Djed ima 90 godina i zaručen je s gospođom od 85. Sestre stalno spavaju, a bratić je prodavač koji prodaje kišobrane u pustinji.",
 text:`{Este*|Esta|Estos::muški rod, jednina → este} es mi abuelo Ramón. Tiene noventa años y es {viudo*|viuda|novio::muškarac kojem je umrla žena → viudo}. Pero ahora tiene novia: una señora de ochenta y cinco años. ¡Están {prometidos*|prometido|prometidas::muškarac + žena → muški rod množine}! {Estas*|Estos|Esta::žene, množina → estas} son {mis*|mi|su::množina → mis} hermanas, Sara y Marta. Ellas {duermen*|dormen|duerme::dormir o→ue, ellas → duermen} doce horas cada día. Mi {primo*|prima|tío::sin od strica/tete (muški) → primo} Lucas es vendedor: vende paraguas en el desierto. Dice que {es*|está|hay::zanimanje/karakter → ser} un genio. Yo no estoy seguro.`},
{id:"s3", g:"rutina, hora, reflexivos", t:"Una mañana terrible", hr:"Paco se budi u 7 manje četvrt, ali nema tople vode. Oblači se, pije kavu i ide na posao. Kasni jer je subota... a subotom ne radi.",
 text:`Paco se {despierta*|desperta|despiertas::despertarse e→ie, él → se despierta} a las siete {menos*|y|de::6:45 = siete MENOS cuarto} cuarto. Se {ducha*|duchas|ducho::él → se ducha}, pero no hay agua caliente. ¡Brrr! Después se {viste*|veste|vistes::vestirse e→i, él → se viste} y toma un café con leche. {Por*|A las|De::bez točnog sata → por} la mañana siempre va al trabajo en bici. Hoy llega a las nueve y media. Su jefe dice: — Paco, ¿qué {haces*|hace|hago::tú → haces} aquí? ¡Hoy es {sábado*|el sábado|sábados::Hoy es + dan (bez člana)}! Paco {vuelve*|volve|vuelvo::volver o→ue, él → vuelve} a casa y se acuesta otra vez.`},
{id:"s4", g:"hay / está, lugar", t:"¿Dónde está el gato?", hr:"Paco traži mačka Rufa po cijelom stanu. Nije na kauču, ni ispod kreveta. Na kraju je u hladnjaku s lubenicom.",
 text:`En el piso de Paco {hay*|está|es::postojanje + un/una → hay} un gato. Se llama Rufo. Paco busca a Rufo. En el salón {hay*|están|es::hay + imenica bez člana} un sofá y dos sillones, pero Rufo no {está*|hay|es::lokacija određene stvari → está} en el sofá. ¿{Está*|Hay|Es::¿Está + ime/određeno?} debajo de la cama? No. ¿Detrás de las cortinas? No. ¿{Dentro*|Fuera|Entre::unutar → dentro de} del armario? Tampoco. Al final Paco abre la nevera. ¡Rufo {está*|hay|son::Rufo (određen) → está} dentro, al lado de la sandía! — Rufo, ¿tienes {calor*|caliente|frío::tener calor = vruće mi je}? — Miau.`},
{id:"s5", g:"restaurante, querer, pedir", t:"En el restaurante", hr:"Paco i Lola večeraju u restoranu. Paco naručuje puno jela i kaže 'Ja častim!', ali na kraju nema novca. Ima osam ruku, ali nula eura.",
 text:`— Buenas noches. ¿Qué van a tomar {de*|en|por::de primero, de segundo, de postre} primero? — Yo de primero {quiero*|quero|quieres::querer e→ie, yo → quiero} gazpacho. — Y yo, sopa de marisco. — ¿Y de segundo? — Para mí, merluza al horno. — Yo {pido*|pedo|pide::pedir e→i, yo → pido} huevos con chorizo, una tortilla de patatas, una hamburguesa y una paella. — ¿Y para {beber*|comer|pagar::para beber = za piće}? — Agua mineral, por favor. Lola dice: «¡Buen {provecho*|viaje|gusto::Buen provecho = dobar tek}!» Después del postre, Paco dice: «¡Yo {invito*|invita|invitas::yo → invito}!». Pero, desafortunadamente, Paco no tiene dinero. Tiene ocho brazos, pero cero euros. — ¿Puedo {pagar*|pago|pagas::poslije 'puedo' → infinitiv} con tarjeta? — No, señor. Pero puede {lavar*|lava|lavas::poslije 'puede' → infinitiv} los platos.`},
{id:"s6", g:"hotel, hay / está", t:"Hotel de cinco estrellas (más o menos)", hr:"Paco dolazi u hotel. Uzima polupansion. Lift ne radi, a soba je na desetom katu. U minibaru ima samo jedno pivo, a ključ je kod recepcije... u drugom gradu.",
 text:`Paco llega al hotel con mucho equipaje. — Buenas tardes. ¿Qué quiere: solo alojamiento, media {pensión*|pensiones|pensión completo::media pensión = polupansion} o todo incluido? — Media pensión, por favor. — Muy bien. Su habitación {está*|hay|es::lokacija → está} en el {décimo*|diez|décima::piso (m.) → décimo} piso. — ¿{Hay*|Está|Es::postojanje → hay} ascensor? — Sí, pero no funciona. Paco sube con sus maletas. En la habitación {hay*|está|son::hay + una} una cama, una tumbona y un minibar. En el minibar hay una cerveza. Solo una. Paco busca la caja fuerte: {está*|hay|es::la caja fuerte (određeno) → está} detrás del cuadro. Paco piensa: «Este hotel es de cinco estrellas... más o menos.»`},
{id:"s7", g:"gustar, también / tampoco", t:"A Lola le gusta todo", hr:"Lola voli sve: ples, filmove strave, adrenalinske sportove. Paco ne voli nogomet, a ni Lola. Paco voli spavati, a Lola ne.",
 text:`A Lola le {gusta*|gustan|gusto::+ infinitiv → gusta} bailar. También le {gustan*|gusta|gustas::+ množina → gustan} las películas de terror y los deportes de riesgo. Paco y Lola hablan: — A mí no me gusta el fútbol. — A mí {tampoco*|también|sí::negacija + slažem se → tampoco}. — Me {gusta*|gustan|gustas::el chocolate (jednina) → gusta} el chocolate. — ¡A mí {también*|tampoco|no::pozitivno + slažem se → también}! — No me gusta levantarme temprano. — A mí {sí*|también|tampoco::ne slažem se s negacijom → sí}. Me encanta. — ¿Y a tus padres? ¿Les gusta ir de excursión? — No, a {ellos*|ellas|él::padres (otac+majka) → ellos} les gusta ver series en el sofá.`},
{id:"s8", g:"imperativo, recetas", t:"Receta: el batido de Paco", hr:"Recept za Pacov smoothie. Oguli bananu, nareži jagode, dodaj borovnice i mlijeko, izmiješaj blenderom. Popij. Ne daj ga mačku.",
 text:`Hoy Paco explica su receta favorita. «Primero, {pela*|pelas|pelar::imperativ tú = oblik za él: pela} un plátano. Después, {corta*|corte|cortas::tú → corta} las fresas. {Añade*|Añada|Añades::tú: añadir → añade} los arándanos y un vaso de leche. {Mezcla*|Mezclas|Mezcle::tú → mezcla} todo con la batidora. ¡Y {bebe*|beba|bebes::tú: beber → bebe}!» Lola pregunta: «¿Y para usted, señor Martínez?» Paco dice con voz formal: «Señor Martínez, {corte*|corta|cortes::usted: -ar → -e} la fruta y {coma*|come|comes::usted: -er → -a} despacio. Y, por favor, no {abra*|abre|abres::usted: -ir → -a} la puerta: el gato Rufo quiere el batido.»`},
{id:"s9", g:"ser / estar", t:"La vecina metiche", hr:"Susjeda Carmen je zabadalo i stalno postavlja osobna pitanja. Paco se šali da je oženjen za osam žena. Carmen je razočarana kad shvati da se šali.",
 text:`Carmen es mi {vecina*|vecino|vecinas::ženski rod → vecina}. Es muy metiche: siempre hace preguntas íntimas. — Paco, ¿{estás*|eres|tienes::bračno stanje → estar casado} casado? — Sí, tengo ocho esposas: una para cada brazo. — ¿De verdad? — No, {estoy*|soy|tengo::estoy bromeando = šalim se} bromeando. Carmen está {decepcionada*|decepcionado|decepcionadas::Carmen (ž.) → -a}. Ella dice que yo {soy*|estoy|tengo::karakter → ser} aburrido. Pero yo no soy aburrido. Yo {estoy*|soy|tengo::trenutno stanje → estar} aburrido cuando ella habla. ¡Es diferente!`}
];
