// type: o-ue | e-ie | e-i | u-ue (stem change) · refl: reflexive · irr: 6 forms override. Optional u: update id.
import type { Verb } from "../../lib/types";

export const VERBS: Verb[] = [
 {inf:"trabajar", hr:"raditi"}, {inf:"comer", hr:"jesti"}, {inf:"vivir", hr:"živjeti"},
 {inf:"hablar", hr:"pričati"}, {inf:"escuchar", hr:"slušati"}, {inf:"cocinar", hr:"kuhati"},
 {inf:"estudiar", hr:"učiti"}, {inf:"descansar", hr:"odmarati"}, {inf:"beber", hr:"piti"},
 {inf:"cenar", hr:"večerati"}, {inf:"desayunar", hr:"doručkovati"}, {inf:"limpiar", hr:"čistiti"},
 {inf:"pagar", hr:"platiti"}, {inf:"caminar", hr:"hodati"}, {inf:"nadar", hr:"plivati"},
 {inf:"bailar", hr:"plesati"}, {inf:"cantar", hr:"pjevati"}, {inf:"viajar", hr:"putovati"},
 {inf:"llegar", hr:"stići"}, {inf:"mirar", hr:"gledati"}, {inf:"tomar", hr:"uzeti, piti"},
 {inf:"leer", hr:"čitati"}, {inf:"aprender", hr:"učiti (naučiti)"}, {inf:"correr", hr:"trčati"},
 {inf:"abrir", hr:"otvoriti"}, {inf:"asistir", hr:"pohađati"}, {inf:"añadir", hr:"dodati"},
 {inf:"cortar", hr:"rezati"}, {inf:"mezclar", hr:"miješati"}, {inf:"pelar", hr:"guliti"},
 {inf:"dormir", hr:"spavati", type:"o-ue"}, {inf:"volver", hr:"vratiti se", type:"o-ue"},
 {inf:"almorzar", hr:"ručati", type:"o-ue"}, {inf:"poder", hr:"moći", type:"o-ue"},
 {inf:"encontrar", hr:"naći", type:"o-ue"}, {inf:"recordar", hr:"sjećati se", type:"o-ue"},
 {inf:"acostarse", hr:"leći", type:"o-ue", refl:true},
 {inf:"empezar", hr:"početi", type:"e-ie"}, {inf:"preferir", hr:"više voljeti", type:"e-ie"},
 {inf:"querer", hr:"htjeti, voljeti", type:"e-ie"}, {inf:"entender", hr:"razumjeti", type:"e-ie"},
 {inf:"mentir", hr:"lagati", type:"e-ie"},
 {inf:"despertarse", hr:"probuditi se", type:"e-ie", refl:true},
 {inf:"sentarse", hr:"sjesti", type:"e-ie", refl:true}, {inf:"sentirse", hr:"osjećati se", type:"e-ie", refl:true},
 {inf:"repetir", hr:"ponoviti", type:"e-i"}, {inf:"pedir", hr:"naručiti, tražiti", type:"e-i"},
 {inf:"vestirse", hr:"obući se", type:"e-i", refl:true},
 {inf:"jugar", hr:"igrati", type:"u-ue"},
 {inf:"levantarse", hr:"ustati se", refl:true}, {inf:"llamarse", hr:"zvati se", refl:true},
 {inf:"ducharse", hr:"tuširati se", refl:true}, {inf:"lavarse", hr:"prati se", refl:true},
 {inf:"afeitarse", hr:"brijati se", refl:true}, {inf:"peinarse", hr:"češljati se", refl:true},
 {inf:"ser", hr:"biti", irr:["soy","eres","es","somos","sois","son"]},
 {inf:"estar", hr:"biti (stanje, mjesto)", irr:["estoy","estás","está","estamos","estáis","están"]},
 {inf:"tener", hr:"imati", irr:["tengo","tienes","tiene","tenemos","tenéis","tienen"], note:"yo: -go, ostalo e→ie"},
 {inf:"ir", hr:"ići", irr:["voy","vas","va","vamos","vais","van"]},
 {inf:"salir", hr:"izaći", irr:["salgo","sales","sale","salimos","salís","salen"], note:"samo yo: salgo"},
 {inf:"saber", hr:"znati", irr:["sé","sabes","sabe","sabemos","sabéis","saben"], note:"samo yo: sé"},
 {inf:"decir", hr:"reći", irr:["digo","dices","dice","decimos","decís","dicen"], note:"yo: -go, plus e→i"},
 {inf:"hacer", hr:"raditi, činiti", irr:["hago","haces","hace","hacemos","hacéis","hacen"], note:"samo yo: hago"}
];
