// [sentence with ___, options, index of correct option, explanation (hr), topic or update id]
import type { Rule } from "../lib/types";

export const RULES: Rule[] = [
["Yo ___ de Croacia.", ["soy","estoy","hay"],0,"Podrijetlo = SER (trajno).",6],
["Hoy ___ muy cansado.", ["soy","estoy","tengo"],1,"Privremeno stanje = ESTAR.",6],
["Mi abuela ___ profesora.", ["es","está","hay"],0,"Zanimanje = SER.",6],
["El café ___ en el armario.", ["hay","está","es"],1,"Lokacija određene stvari (el café) = ESTAR.",20],
["En la cocina ___ un microondas.", ["hay","está","es"],0,"Postojanje + un/una = HAY.",20],
["¿___ leche en el frigorífico?", ["Hay","Está","Es"],0,"HAY + imenica bez člana.",20],
["Las llaves ___ encima de la mesa.", ["están","hay","son"],0,"las llaves (određeni član) + mjesto = ESTÁN.",20],
["En el salón ___ dos sillas.", ["hay","están","son"],0,"HAY + broj + imenica. HAY nikad s el/la/los/las!",20],
["A mí me ___ el chocolate.", ["gusta","gustan","gusto"],0,"Jednina (el chocolate) → GUSTA.",26],
["A mí me ___ los perros.", ["gusta","gustan","gustas"],1,"Množina (los perros) → GUSTAN.",26],
["A ella ___ gusta bailar.", ["le","me","se"],0,"a ella → LE gusta. Infinitiv → gusta.",26],
["A nosotros ___ gustan las series.", ["nos","os","les"],0,"a nosotros → NOS.",26],
["— No me gusta el fútbol. — A mí ___.", ["tampoco","también","sí"],0,"Negativna rečenica + slažem se = TAMPOCO.",21],
["— Me gusta nadar. — A mí ___.", ["también","tampoco","no también"],0,"Pozitivna + slažem se = TAMBIÉN.",21],
["— Yo no bebo café. — Yo ___.", ["tampoco","también","no"],0,"Yo + negacija → Yo tampoco.",21],
["— A mí no me gusta estudiar. — A mí ___.", ["sí","también","tampoco"],0,"Ne slažem se s negacijom → A mí SÍ.",26],
["___ la mañana voy al trabajo.", ["Por","A las","De"],0,"Bez točnog sata → POR la mañana.",14],
["Tomo café ___ ocho.", ["a las","por las","en las"],0,"Točno vrijeme → A LAS.",14],
["Trabajo desde las ocho ___ las cuatro.", ["hasta","a","de"],0,"DESDE ... HASTA ... (s las).",14],
["Trabajo de ocho ___ cuatro.", ["a","hasta","por"],0,"DE ... A ... (bez las).",14],
["___ la una y media.", ["Es","Son","Está"],0,"1 sat → ES LA una.",10],
["___ las tres menos cuarto.", ["Son","Es","Está"],0,"2+ sata → SON LAS.",10],
["¿___ es tu número de teléfono?", ["Cuál","Qué","Cómo"],0,"CUÁL + glagol (es).",5],
["¿___ libro lees?", ["Qué","Cuál","Cuánto"],0,"QUÉ + imenica.",5],
["Este es ___ hermano.", ["mi","mis","mía"],0,"Jedna stvar → MI.",8],
["Son ___ libros.", ["tus","tu","tuyo"],0,"Množina → TUS.",8],
["___ son mis primas.", ["Estas","Estos","Este"],0,"Žene, množina → ESTAS.",8],
["___ son Ana y Pablo.", ["Estos","Estas","Esta"],0,"Mješovita grupa → muški rod ESTOS.",8],
["Ella es ___.", ["francesa","francés","franceso"],0,"francés → francesa (+a, bez naglaska).",4],
["Él es ___.", ["alemán","alemana","alemano"],0,"Muški: alemán. Ženski: alemana.",4],
["Ella es ___.", ["croata","croato","croatesa"],0,"-a ostaje isto za oba roda: croata, belga.",4],
["Ella es ___.", ["periodista","periodisto","periodistora"],0,"-ista je isto za oba roda.",4],
["Ella es ___.", ["profesora","profesor","profesoresa"],0,"-or → -ora.",4],
["Ella es ___.", ["camarera","camarero","camarer"],0,"-o → -a.",4],
["Tengo dos ___.", ["relojes","relojs","reloj"],0,"Završava na suglasnik → +ES.",7],
["Hay tres ___.", ["cruces","cruzes","cruzs"],0,"-z → -ces.",7],
["Tengo ___ hermana y dos hermanos.", ["una","un","uno"],0,"Ženski rod → UNA.",8],
["Vivo en el ___ piso.", ["tercer","tercero","tercera"],0,"Ispred muške imenice: primer, tercer (bez -o).",18],
["Vivo en la ___ planta.", ["primera","primer","primero"],0,"Ženski rod: primera planta.",18],
["La sopa está ___.", ["caliente","calor","frío"],0,"Stvar je vruća: está caliente. Za sebe reci TENGO CALOR (estoy caliente = nepristojno!).",19],
["Hoy ___ calor.", ["tengo","estoy","soy"],0,"Osjećaj vrućine: TENGO calor / frío / sueño.",19],
["La película es muy larga, ___ aburrido.", ["estoy","soy","tengo"],0,"Dosađujem se (stanje) → ESTOY aburrido. 'Soy aburrido' = dosadan sam (karakter)!",16],
["Mi amigo es muy ___: saca un 10 en el examen.", ["listo","lista","listos"],0,"SER listo = pametan. ESTAR listo = spreman.",17],
["(tú) ¡___ la puerta, por favor!", ["Abre","Abra","Abres"],0,"Imperativ tú = oblik za él: abre.",24],
["(usted) ¡___ la fruta, por favor!", ["Corte","Corta","Cortas"],0,"Imperativ usted: -ar → -e (corte).",24],
["(usted) ¡___ un poco más!", ["Coma","Come","Comes"],0,"Imperativ usted: -er → -a (coma).",24],
["¿___ a qué hora empieza la clase?", ["Sabes","Sabe","Sé"],0,"tú → sabes.",23],
["Yo no ___ nada.", ["sé","sabo","sabes"],0,"saber, yo → SÉ (nepravilno).",23],
["Yo ___ un café con leche.", ["pido","pedo","pide"],0,"pedir e→i: pido. (pedo znači nešto drugo!)",23],
["Los fines de semana ___ con amigos.", ["salgo","salo","sale"],0,"salir, yo → SALGO.",13],
["Nosotros ___ ocho horas.", ["dormimos","duermimos","duermen"],0,"Nosotros je IZVAN 'čizme': nema promjene o→ue.",13],
["Ella ___ al fútbol.", ["juega","juga","jugua"],0,"jugar u→ue: juega.",13],
["Yo me ___ a las siete.", ["despierto","desperto","despierta"],0,"despertarse e→ie: me despierto.",13],
["¿A qué hora te ___?", ["levantas","levanta","levantes"],0,"tú + -ar → -as: te levantas.",11],
["Ellos se ___ los dientes.", ["lavan","lava","lavamos"],0,"ellos → se + -an.",11],
["___ tienes hambre, come algo.", ["Si","Sí","Se"],0,"SI bez naglaska = ako. SÍ = da.",14]
];
